### ISSUE TITLE
Send invoice to client

### ISSUE THREAD

**Issue by vinyll** [etceterra/aposto-app#1]
Let's use a service like sendinblue or other to send receipts to the client and the therapist in bcc

**Comment by vinyll** [comment]
Documentation for Sendinblue: https://developers.sendinblue.com/reference#sendtransacemail

**Comment by mlbiche** [comment]
Fixed in [commit 508572d773eca1caa0e5b81806f9c3b46f3c2704](https://github.com/etceterra/aposto-app/commit/508572d773eca1caa0e5b81806f9c3b46f3c2704)
