### ISSUE TITLE
Define "Anamnèse" therapy as default

### ISSUE THREAD

**Issue by mlbiche** [etceterra/aposto-app#11]
Most therapist use "Anamnèse" therapy during each session.

**Comment by mlbiche** [comment]
@vinyll I am facing an issue by setting "Anamnèse" as default which is that on first logged/demo mode, as "Anamnèse" is set by default, the _Preferred therapies_ user panel section is considered as valid (there is at least one preferred therapy, which is "Anamnèse") so it is closed . This way therapists could not easily see this section at this step while it is important.
A solution would be to consider a set of preferred therapies containing only "Anamnèse" as invalid. What do you think about it ?

**Comment by vinyll** [comment]
>  solution would be to consider a set of preferred therapies containing only "Anamnèse" as invalid.
👍
