### ISSUE TITLE
Update user panel from accordion to double-slider on desktop

### ISSUE THREAD

**Issue by mlbiche** [etceterra/aposto-app#14]

**Comment by mlbiche** [comment]
I am not sure about the double-slider... The user panel is already quite complicated as it is, with all the expansion panel management. Not sure if it is wise to make it even bigger and more complicated just to have this fancy double-slider... 🤔

**Comment by vinyll** [comment]
Complication = wrong way.
Maybe the desktop should not have the slider at all?

**Comment by mlbiche** [comment]
By wrong way, you mean we shouldn't go this way or it is designed the wrong way (IMO, both meaning are actually corresponding to the situation... 😕
By not slider at all, you mean having a dedicated page for authentication and user informations ?

**Comment by vinyll** [comment]
wrong way for whatever reason, there's something to change, code-wise or interface-wise.
No slider at all on desktop could imply having the panel open. Just as a side container.

**Comment by mlbiche** [comment]
In fact, the complexity is not due to the slider as it is abstracted by Material. It is all the interaction between the view, the slider and the expansion panels that makes it complex. But I can definitely give a try to the side container on desktop.

**Comment by mlbiche** [comment]
Too complex. Abort !
