### ISSUE TITLE
Actions at the end of process

### ISSUE THREAD

**Issue by vinyll** [etceterra/aposto-app#2]
When the form is valid, invite the therapist to:
- send the invoice
- download the invoice
- start a new invoice

**Comment by mlbiche** [comment]
Is "Start a new invoice" really needed as there is the reload with the success alert ?

**Comment by vinyll** [comment]
Actually I've started implementing the actions changing the display for "download" and "start" and adding a disabled button for "send".
I guess it's an explicit feature for a user to choose what to do.
He could send the invoice then start a new one, or print it then start over, or just send and close for example…

**Comment by mlbiche** [comment]
Ok sounds good to me. Then the success alert for the download has to be brought down after the form or as a modal (but modal is a pain for the user) so the user see it without going back to the top of the page.

**Comment by vinyll** [comment]
Actually the current action to start a new invoice is to reload the page. We could eventually refresh with a `?success=1` if needed though I'm not sure we need it in this case.

An alert will be essential for confirming the email was sent though (and confirming the download similarly to what you did already)

**Comment by mlbiche** [comment]
Fixed in [commit 7c926cf9ab74bed50ce33b3a645da9e3b414a43e](https://github.com/etceterra/aposto-app/commit/7c926cf9ab74bed50ce33b3a645da9e3b414a43e)
